package vista.gerente;

import javax.swing.JButton;

/**
 *
 * @author Johnny
 */
public class GerenteNvPnl extends javax.swing.JPanel {

    /**
     * Creates new form pnlMenu
     */
    public GerenteNvPnl() {
        initComponents();
    }

    public JButton getBtnContratos() {
        return btnContratos;
    }

    public JButton getBtnMenu() {
        return btnMenu;
    }

    public JButton getBtnPagos() {
        return btnPagos;
    }

    public JButton getBtnPlatos() {
        return btnPlatos;
    }

    public JButton getBtnReportes() {
        return btnReportes;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReportes = new javax.swing.JButton();
        btnContratos = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        btnPlatos = new javax.swing.JButton();

        setBackground(new java.awt.Color(60, 99, 130));
        setMinimumSize(new java.awt.Dimension(600, 35));
        setPreferredSize(new java.awt.Dimension(600, 35));

        btnReportes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(204, 204, 204));
        btnReportes.setText("Reportes");
        btnReportes.setBorder(null);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.setFocusPainted(false);

        btnContratos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnContratos.setForeground(new java.awt.Color(204, 204, 204));
        btnContratos.setText("Contratos");
        btnContratos.setBorder(null);
        btnContratos.setContentAreaFilled(false);
        btnContratos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContratos.setFocusPainted(false);

        btnMenu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(204, 204, 204));
        btnMenu.setText("Menu");
        btnMenu.setBorder(null);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setFocusPainted(false);

        btnPagos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPagos.setForeground(new java.awt.Color(204, 204, 204));
        btnPagos.setText("Pagos");
        btnPagos.setBorder(null);
        btnPagos.setContentAreaFilled(false);
        btnPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPagos.setFocusPainted(false);

        btnPlatos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPlatos.setForeground(new java.awt.Color(204, 204, 204));
        btnPlatos.setText("Platos");
        btnPlatos.setBorder(null);
        btnPlatos.setContentAreaFilled(false);
        btnPlatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlatos.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContratos;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPagos;
    private javax.swing.JButton btnPlatos;
    private javax.swing.JButton btnReportes;
    // End of variables declaration//GEN-END:variables
}
